### ISSUE TITLE
Article (just sharing not an issue )

### ISSUE THREAD

**Issue by amrrs** [hrbrmstr/wiglr#2]
Thanks @hrbrmstr for this!

Hope you're okay with this piece!

https://towardsdatascience.com/building-a-wifi-spots-map-of-networks-around-you-with-wigle-and-r-d01a73b1172d

**Comment by hrbrmstr** [comment]
wow! what a map! great post!

**Comment by hrbrmstr** [comment]
ZOMGOSH #ty! (and glad you had fun with the pkg!)

**Comment by amrrs** [comment]
Thank you :) for the kind words!
